In [1]:
import numpy as np

In [2]:
def power_method_find(A :list,x0: list,tol = 1e-6):
    '''
    # Power Method
    This function finds the largest eigenvalue and the corresponding eigenvector

    ## Condition
    - n x n matrix A has n linearly independent eigenvectors
    - Eigenvalues can be ordered in magnitude : |λ1| > |λ2| > · · · > |λn|. The λ1 is called the dominant eigenvalue and the corresponding eigenvector is the dominant eigenvector of A.

    ## Paremeters
    - A: The matrix for which the eigenvalues and eigenvectors are to be found
    - x0: The initial guess for the eigenvector
    - tol: The tolerance for the solution
    ## Returns
    - eigval: The largest eigenvalue
    - eigvec: The corresponding eigenvector
    '''
    A=np.array(A)
    x0=np.array(x0)
    x_copy = np.copy(x0)
    lam_0 = np.matmul(np.matmul(np.linalg.matrix_power(A,2),x0).T,np.matmul(np.linalg.matrix_power(A,1),x0))[0][0]/np.matmul(np.matmul(np.linalg.matrix_power(A,1),x0).T,np.matmul(np.linalg.matrix_power(A,1),x0))[0][0]
    lam_1 = np.matmul(np.matmul(np.linalg.matrix_power(A,3),x0).T,np.matmul(np.linalg.matrix_power(A,2),x0))[0][0]/np.matmul(np.matmul(np.linalg.matrix_power(A,2),x0).T,np.matmul(np.linalg.matrix_power(A,2),x0))[0][0]
    i=3
    while abs(lam_1-lam_0)>tol:
        lam_0 = lam_1
        lam_1 = np.matmul(np.matmul(np.linalg.matrix_power(A,i+1),x0).T,np.matmul(np.linalg.matrix_power(A,i),x0))[0][0]/np.matmul(np.matmul(np.linalg.matrix_power(A,i),x0).T,np.matmul(np.linalg.matrix_power(A,i),x0))[0][0]
        i+=1

    eigval = lam_1
    eigvec = np.matmul(np.linalg.matrix_power(A,i-1),x_copy)
    norm = np.linalg.norm(eigvec)
    eigvec = eigvec/norm
    return eigval,eigvec,i    


A = np.array([
    [4,    2/3, -4/3, 4/3],
    [2/3,   4,   0,    0],
    [-4/3,  0,   6,    2],
    [4/3,   0,   2,    6]
    ])


x0 =np.array([[4],[3],[7],[9]])


val,vec = np.linalg.eigh(A)
print(val)

print(power_method_find(A,x0))


# print(np.matmul(np.linalg.matrix_power(A,1),x0))

# print(x0.T)

# print(np.matmul(np.matmul(np.linalg.matrix_power(A,2),x0).T,x0)[0[0][0]][0])



[2. 4. 6. 8.]
(7.999999002873864, array([[4.99281015e-04],
       [1.66473835e-04],
       [7.06773763e-01],
       [7.07439447e-01]]), 23)


In [9]:
import numpy as np



# Example usage:
A = np.array([[1, -1, 4], [2, 3, -1], [3, 1, 2]])
Q, R = QR_factorize(A)
print("Q:")
print(Q)
print("R:")
print(R)



P,U = np.linalg.qr(A)

print("Q")
print(P)

print("R")
print(U)


Q:
[[ 0.26726124 -0.61977979  0.73786479]
 [ 0.53452248  0.73246702  0.42163702]
 [ 0.80178373 -0.28171808 -0.52704628]]
R:
[[ 3.74165739  2.13808994  2.13808994]
 [ 0.          2.53546276 -3.77502234]
 [ 0.          0.          1.47572957]]
Q
[[-0.26726124  0.61977979 -0.73786479]
 [-0.53452248 -0.73246702 -0.42163702]
 [-0.80178373  0.28171808  0.52704628]]
R
[[-3.74165739 -2.13808994 -2.13808994]
 [ 0.         -2.53546276  3.77502234]
 [ 0.          0.         -1.47572957]]


In [ ]:
n = 50
m = 0.2
# define the delta function
def delta(i, j):
    return 1 if i == j else 0

# define the A matrix
def A_ij(i, j, mu = 1, m = 0.2):
    return 0.5 * (delta(i + mu, j) + delta(i - mu, j)- 2*delta(i, j)) + m**2 * delta(i, j) if not ((i == 0 and j == n-1) or (i == n-1 and j == 0)) else 0.5   # impose periodic boundary conditions