In [2]:
import numpy as np

In [9]:
def Singlular_value_decompose(A):
    """
    Compute the Singular Value Decomposition (SVD) of a matrix A.
    
    Parameters:
    A (list of lists): The input matrix.
    
    Returns:
    U (list of lists): The left singular vectors.
    s (list): The singular values.
    V (list of lists): The right singular vectors.
    """
    A = np.array(A)
    # Get the dimensions of the matrix
    m, n = len(A), len(A[0])
    
    # Step 1: Compute the covariance matrix A^T A
    A_T = A.T
    A_T_A = np.matmul(A_T, A)
    
    # Step 2: Find the eigenvalues and eigenvectors of the covariance matrix
    eigenvalues, eigenvectors = np.linalg.eigh(A_T_A)
    
    # Step 3: The singular values s are the square roots of the eigenvalues
    s = [np.sqrt(ev) for ev in eigenvalues]
    
    # Step 4: The left singular vectors U are the eigenvectors of A A^T
    A_A_T = np.matmul(A, A_T)
    l,U = np.linalg.eigh(A_A_T)
    
    # Step 5: The right singular vectors V are the eigenvectors of A^T A
    V = eigenvectors
    
    return U, s, V






# Example usage
A = [
    [3, 2, 2], 
    [2, 3, -1]
    ]

U,s,V= np.linalg.svd(A)

print("U:\n", U)
print("Σ:\n", [s])
print("V^T:\n", V)


U, s, V = Singlular_value_decompose(A)





print("U:\n", U)
print("Σ:\n", [s])
print("V^T:\n", V)




U:
 [[-0.75774021 -0.65255634]
 [-0.65255634  0.75774021]]
Σ:
 [array([5.06081754, 2.32123368])]
V^T:
 [[-0.70706625 -0.68628229 -0.17051081]
 [-0.19049723  0.41706613 -0.88868816]
 [-0.68100522  0.59587957  0.42562827]]
U:
 [[ 0.65255634 -0.75774021]
 [-0.75774021 -0.65255634]]
Σ:
 [[5.8872553070184244e-08, 2.3212336788702808, 5.06081754344872]]
V^T:
 [[-0.68100522  0.19049723 -0.70706625]
 [ 0.59587957 -0.41706613 -0.68628229]
 [ 0.42562827  0.88868816 -0.17051081]]
